baseURL = "https://beny23.github.io/"
languageCode = "en-gb"
title = "Tales about Software Engineering"
copyright = "Software Design Systems"
theme = "ananke"
googleAnalytics = ""

[params]
  favicon = ""
  site_logo = ""
  description = "Writings about software: development and security"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/beny23"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/gerald-benischke-9811b663"
  mastodon = "https://infosec.exchange/@beny23"
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/227140/beny23"
  rss = ""
  show_reading_time = true
  featured_image = "/images/background.png"
  recent_posts_number = 6

[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Talks"
    weight = 3
    url  = "/talks/"
[[menu.main]]
    name = "Tags"
    weight = 4
    url  = "/tags/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 2
